services:
#    intranet.example:
#        class: IntranetBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  intranet.form.note:
        class: IntranetBundle\Form\NoteType
        arguments: ["@doctrine.orm.entity_manager", "@fos_user.user_manager"]
        tags:
            - { name: form.type }
